language: node_js
node_js:
  - "8"
  
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-js.conf --only=features,step_definitions --test-run-id=188700"
  - npm install

script:
  - node_modules/.bin/cucumber-js --format=json | node_modules/cucumber-junit/bin/cucumber-junit --features-as-suites > junit_output.xml

after_script:
<<<<<<< HEAD
  - hiptest-publisher -c cucumber-js.conf  --push=junit_output.xml --test-run-id=188700
=======
  - hiptest-publisher -c cucumber-js.conf --push=junit_output.xml --test-run-id=188700
>>>>>>> 94d429c0c1b2729bd42953799f06cf222f3ecb99


