language: node_js
cache: bundler
node_js:
  - "8"
  
sudo: false

before_install:
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-js.conf --token=97021262407624878220258698178607794102268586029598435361 --only=tests --test-run-id=398005"
  - npm install

script:
  - node_modules\.bin\cucumber-js --format=json | node node_modules\cucumber-junit\bin\cucumber-junit --features-as-suites > json_output.xml

after_script:
  - hiptest-publisher -c cucumber-js.conf --token=97021262407624878220258698178607794102268586029598435361 --push=json_output.xml --test-run-id=398005
